/* Renders press links by calling proxy service for each press link in this list */
export const pressLinks = [
  "https://www.photogroupie.com/post/river-nelson-altobeats-mindfulness",
  "https://pipilopop.com/river-nelson-alto-beats-presentan-su-nuevo-album-we-should-escape/",
  "https://kcuhhp.blogspot.com/2023/10/river-nelson-altobeats-seclusion.html?spref=tw",
  "https://versevanguard.com/river-nelson-alto-beats-we-should-escape-release/",
  "https://www.dopefuture.com/2023/10/river-nelson-alto-beats-drop-we-should.html",
  "https://www.hiphopovereverything.com/post/river-nelson-and-alto-beats-proudly-drop-their-brand-new-studio-album-we-should-escape",
  "https://www.pressparty.com/pg/newsdesk/andyk/view/354417/",
  "https://www.hhheadz.com/2023/10/river-nelson-and-alto-beats-proudly.html",
  "https://definitionoffresh.blogspot.com/2023/10/river-nelson-alto-beats-we-should-escape.html?spref=tw",
  "https://blackouthiphop.com/blog/river-nelson-altobeats-mindfulness/",
  "https://jammerzine.com/river-nelson-mindfulness/",
  "https://www.faded4u.com/2023/09/river-nelson-alto-beats-drop-incredible.html",
  "https://www.allmusicvidz.com/river-nelson-altobeats-mindfulness-music-video/",
  "https://www.rapstarvidz.com/river-nelson-altobeats-mindfulness-music-video/",
  "https://www.yomusic.co/river-nelson-altobeats-mindfulness-music-video/",
  "https://tinnitist.com/2023/09/13/river-nelson-altobeats-bring-mindfulness-to-their-music/",
  "https://oldtothenew.wordpress.com/2023/09/09/new-joint-river-nelson-altobeats-2/",
  "https://www.hiphopovereverything.com/post/river-nelson-alto-beats-drops-incredible-animated-visual-today-for-mindfulness",
  "https://definitionoffresh.blogspot.com/2023/09/video-river-nelson-altobeats-mindfulness.html?spref=tw",
  "https://pipilopop.com/river-nelson-alto-beats-presentan-su-nuevo-sencillo-y-video-mindfulness/",
  "https://www.pressparty.com/pg/newsdesk/andyk/view/348876/",
  "https://www.hhheadz.com/2023/09/river-nelson-alto-beats-drop-incredible.html",
  " https://platinummind.net/index.php/2023/09/08/single-review-mindfulness-river-nelson/",
  "https://blackouthiphop.com/blog/river-nelson-ft-blu-treasures-remix/",
  "https://www.wordplaymagazine.com/blog-1/2022/6/14/river-nelson-ft-blu-treasures-remix-single",
  "https://blackouthiphop.com/blog/video-river-nelson-altobeats-greatest-of-lights/",
  "https://beatboxradioshow.blogspot.com/2021/11/river-nelson-like-sun-didnt-sink-2021.html",
  "https://jammerzine.com/first-look-river-nelson-altobeats-greatest-of-lights/",
  "https://definitionoffresh.blogspot.com/2021/11/video-river-nelson-altobeats-greatest.html",
  "https://urbanvault.co.uk/2021/11/01/river-nelson-altobeats-greatest-of-lights-music-video-taken-off-like-the-sun-didnt-sink-album-itunes-spotify/",
  "https://www.rapstarvidz.com/river-nelson-greatest-of-lights/",
  "https://insomniacmagazine.com/river-nelson-altobeats-drop-greatest-of-lights-video/",
  "https://tinnitist.com/2021/10/29/weekend-mixtape-side-7-216-songs-that-are-nothing-but-a-treat/",
  "https://www.pressparty.com/pg/newsdesk/andyk/view/272310/",
  "https://www.wordplaymagazine.com/blog-1/2021/9/17/si7vgtc66h1i3740z05zveqgrt1d4o",
  "https://www.dmt.news/2021/10/video-river-nelson-altobeats-new-view.html?m=1",
  "https://definitionoffresh.blogspot.com/2021/09/video-river-nelson-altobeats-new-view.html",
  "https://jammerzine.com/first-look-river-nelson-altobeats-new-view/",
  "https://fomoblog.com/2021/09/23/river-nelson-has-a-new-view/",
  "https://www.able2uk.com/news/music/river-nelson-shares-his-mental-health-story",
  "https://platinummind.net/index.php/2021/09/22/blog-interview-river-nelson/",
  "http://www.ok-tho.com/2021/09/river-nelson-altobeats-new-view.html?spref=tw",
  "https://tinnitist.com/2021/09/17/weekend-mixtape-side-8-234-songs-that-will-keep-you-busy-until-monday/",
  "https://www.pressparty.com/pg/newsdesk/andyk/view/268120/",
  "https://top40-charts.com/news.php?nid=175258"
];


/* Renders youtube videos on homepage */
export const youtubeVideoIds = [
  "vnLcmgYMRVo",
  "3ZQgBOCCCPc",
  "EMKJ0qioU1A",
  "3PmQQ68-ZJQ",
  "kJPcX0N0k2Q",
  "vi4SsFpMa4o",
];

